# https://limxw.com/post/build-docker-image-in-multi-archs-with-github-actions/
# https://web.archive.org/web/20210705074149/https://limxw.com/post/build-docker-image-in-multi-archs-with-github-actions/
name: build

on:
  workflow_dispatch: 
  schedule:
    - cron: "30 22 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #- name: Login to GitHub Container Registry
      #  uses: docker/login-action@v1
      #  with: 
      #    registry: ghcr.io
      #    username: ${{ github.repository_owner }}
      #    password: ${{ secrets.CR_PAT }}
      - name: Build Xray-core
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
          push: true
          tags: |
            chenjicheng/xray-core:latest
